src = "src/{name}.bdf"
out_dir = "img"
txt_dir = "txt"
accents = false
chars = "chars"
map = "map"
gens = []
font_size = 16

[clrs]
bg = "#000000"
fg = "#d0d0d0"

base = [
  "#000000",
  "#ff0000",
  "#33ff00",
  "#ff0099",
  "#0066ff",
  "#cc00ff",
  "#00ffff",
  "#d0d0d0",

  "#808080",
  "#ff0000",
  "#33ff00",
  "#ff0099",
  "#0066ff",
  "#cc00ff",
  "#00ffff",
  "#ffffff",
]
