src = "src/{name}.bdf"
out_dir = "img"
txt_dir = "txt"
hide_accents = true
gens = []
font_size = 16

[chars]
out = "chars"
width = 48

[map]
out = "map"
label_clrs = ["1", "5"]
border_clr = "8"

[clrs]
bg = "#161616"
fg = "#ffffff"
base = [
  "#222222",
  "#e84f4f",
  "#b7ce42",
  "#fea63c",
  "#66aabb",
  "#b7416e",
  "#6d878d",
  "#dddddd",
  "#666666",
  "#d23d3d",
  "#bde077",
  "#ffe863",
  "#aaccbb",
  "#e16a98",
  "#42717b",
  "#cccccc",
]
