# This is an annotated example bited-build config.

[[fonts]]

# Font name.
# Required.
name = "Cool Font"

# Go template denoting a path to the bited BDF relative to the config.
# - Name: font name.
# Defaults to `src/{{ .Name }}.bdf`.
src = "src/{{ .Name }}.bdf"

# Path to the output folder relative to the config.
# Defaults to `out`.
out_dir = "out"

# Suffix to append to family names of built vector formats
# (i.e. `name + suffix`).
# Defaults to ` Vec`.
vec_suffix = " Vec"

# Suffix to append to family names of built OTB formats
# (i.e. `name + suffix`).
# Defaults to empty string.
otb_suffix = " OTB"

# Suffix to append to family names of built DFONT formats
# (i.e. `name + suffix`).
# Defaults to empty string.
dfont_suffix = " DFONT"

# Suffix to append to family names of built PCF formats
# (i.e. `name + suffix`).
# Defaults to ` PCF`.
dfont_suffix = " PCF"

# Array of integer scales to target when building to bitmap formats.
# Defaults to `[]`.
xs = [2, 3]

# Go template denoting the font name when building scaled bitmaps.
# - Name: font name.
# - X: integer scale.
# Defaults to `{{ .Name }}{{ .X }}x`.
x_format = "{{ .Name }}{{ .X }}x"

# Language to use when generating the font's SFNT names table.
# Defaults to `English (US)`.
sfnt_lang = "English (US)"

# Python snippet that is injected into the FontForge build script.
# `f` holds the font being built.
# Defaults to `""`.
ttfix = '''
f.os2_version = 4
f.os2_vendor = "XYZ"
f.os2_panose = (0, 0, 0, 9, 0, 0, 0, 0, 0, 0)
f.os2_weight_width_slope_only = True
'''

# Key-value pairs that correspond to fields in the generated SFNT names table.
# Defaults to `{}`.
[fonts.sfnt]
"UniqueID" = "johndoe: Cool Font: 2025"
"Vendor URL" = "https://example.com/cool_font"
"Designer" = "John Doe"
"Designer URL" = "https://example.com"
"License" = "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"
"License URL" = "https://scripts.sil.org/OFL"

# Multiple fonts can be defined in one config.

[[fonts]]
name = "Cool Font Bold"
xs = [2, 3]
ttfix = '''
f.os2_version = 4
f.os2_vendor = "XYZ"
f.os2_panose = (0, 0, 0, 9, 0, 0, 0, 0, 0, 0)
f.os2_weight_width_slope_only = True
'''

[fonts.sfnt]
"UniqueID" = "johndoe: Cool Font Bold: 2025"
"Vendor URL" = "https://example.com/cool_font"
"Designer" = "John Doe"
"Designer URL" = "https://example.com"
"License" = "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"
"License URL" = "https://scripts.sil.org/OFL"
